export const ROLES = {
    ADMIN: 'ADMIN',
    MANAGER: 'MANAGER',
    MARKETING_EXEC: 'MARKETING_EXEC',
    SERVICE_EXEC: 'SERVICE_EXEC',
    CUSTOMER: 'CUSTOMER'
};

export const ROLE_HIERARCHY = {
    ADMIN: ['ADMIN', 'MANAGER', 'MARKETING_EXEC', 'SERVICE_EXEC'],
    MANAGER: ['MANAGER', 'MARKETING_EXEC', 'SERVICE_EXEC'],
    MARKETING_EXEC: ['MARKETING_EXEC'],
    SERVICE_EXEC: ['SERVICE_EXEC'],
};
